### ISSUE TITLE
error TS5024: Compiler option 'declaration' requires a value of type boolean.

### ISSUE THREAD

**Issue by xmlking** [angular/react-native-renderer#69]
node -v
v6.2.2
 npm -v
3.9.5
Env: Mac 

I did fresh install as per instructions: i.e.,`npm install -g gulp react-native-cli typings` and `npm install` successful but after trying to start, it fails with  following  errors: 

```
$ gulp start.ios
(node:5991) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[21:33:29] Using gulpfile /Developer/Work/mobile/react-native-renderer/gulpfile.js
[21:33:29] Starting '!assets'...
[21:33:29] Starting 'watch'...
[21:33:29] Finished '!assets' after 48 ms
[21:33:29] Starting '!transpile'...
error TS5024: Compiler option 'declaration' requires a value of type boolean.
sample/samples/android/apis.ts(72,13): error TS2339: Property 'isConnectionExpensive' does not exist on type 'NetInfoStatic'.
sample/samples/ios/apis.ts(65,13): error TS2339: Property 'isConnectionExpensive' does not exist on type 'NetInfoStatic'.
sample/samples/ios/apis.ts(93,7): error TS2345: Argument of type '{ title: string; options: string[]; cancelButtonIndex: number; destructiveButtonIndex: number; ti...' is not assignable to parameter of type 'ActionSheetIOSOptions'.
  Object literal may only specify known properties, and 'tintColor' does not exist in type 'ActionSheetIOSOptions'.
sample/samples/ios/apis.ts(102,7): error TS2345: Argument of type '{ url: string; message: string; subject: string; }' is not assignable to parameter of type 'ShareActionSheetIOSOptions'.
  Object literal may only specify known properties, and 'subject' does not exist in type 'ShareActionSheetIOSOptions'.
sample/samples/ios/apis.ts(126,78): error TS2345: Argument of type '({ text: string; onPress: () => void; style: string; } | { text: string; onPress: (password: any)...' is not assignable to parameter of type 'AlertIOSButton[]'.
  Type '{ text: string; onPress: () => void; style: string; } | { text: string; onPress: (password: any) ...' is not assignable to type 'AlertIOSButton'.
    Type '{ text: string; onPress: () => void; style: string; }' is not assignable to type 'AlertIOSButton'.
      Object literal may only specify known properties, and 'style' does not exist in type 'AlertIOSButton'.
src/angular2-react-native.d.ts(3,3): error TS2439: Import or export declaration in an ambient module declaration cannot reference module through relative module name.
src/angular2-react-native.d.ts(3,17): error TS2307: Cannot find module './index'.
src/components/picker.ts(66,9): error TS7017: Index signature of object type implicitly has an 'any' type.
src/components/scrollview.ts(61,14): error TS2415: Class 'ScrollView' incorrectly extends base class 'HighLevelComponent'.
  Types have separate declarations of a private property '_removeClippedSubviews'.
src/events/hammer.ts(67,34): error TS7009: 'new' expression, whose target lacks a construct signature, implicitly has an 'any' type.
src/renderer/bootstrap.ts(15,8): error TS2656: Exported external package typings file '/Developer/Work/mobile/react-native-renderer/node_modules/zone.js/dist/zone.js.d.ts' is not a module. Please contact the package author to update the package definition.
src/test_helpers/utils.ts(72,3): error TS7017: Index signature of object type implicitly has an 'any' type.
[21:33:31] Finished '!transpile' after 2.47 s
[21:33:31] Starting '!copyToNodeModules'...
[21:33:31] Finished '!copyToNodeModules' after 38 ms
[21:33:31] Starting '!compile'...
[21:33:31] Finished '!compile' after 16 ms
[21:33:31] Starting '!launch.ios'...
{ Error: Command failed: react-native run-ios
Command `run-ios` unrecognized. Did you mean to run this inside a react-native project?

    at ChildProcess.exithandler (child_process.js:207:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'react-native run-ios' }
[21:33:31] Finished '!launch.ios' after 127 ms
```

**Comment by mlaval** [comment]
The error `error TS5024: Compiler option 'declaration' requires a value of type boolean.` is not a problem, it doesn't prevent the project to work fine.

Did you run `gulp init` before `gulp start.ios` ?

**Comment by mlaval** [comment]
Closing, please re-open if it still happens after running `gulp init` before `gulp start.ios`
